<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MasterKategori;
use App\Models\MasterLokasi;
use App\Models\MasterKondisi;
use App\Models\MasterPengelola;
use App\Models\DataAsetKolektif;

class MasterDataSeeder extends Seeder
{
    public function run(): void
    {
        // Seed Master Kategori
        $kategoriData = [
            ['nama_kategori' => 'Elektronik', 'deskripsi' => 'Peralatan elektronik dan teknologi'],
            ['nama_kategori' => 'Furniture', 'deskripsi' => 'Mebel dan perabotan'],
            ['nama_kategori' => 'Sound System', 'deskripsi' => 'Peralatan audio dan suara'],
            ['nama_kategori' => 'Multimedia', 'deskripsi' => 'Peralatan multimedia dan proyeksi'],
            ['nama_kategori' => 'Musik', 'deskripsi' => 'Alat musik dan perlengkapannya'],
            ['nama_kategori' => 'Dekorasi', 'deskripsi' => 'Ornamen dan dekorasi ruangan'],
            ['nama_kategori' => 'Liturgi', 'deskripsi' => 'Perlengkapan ibadah dan liturgi'],
            ['nama_kategori' => 'Keamanan', 'deskripsi' => 'Peralatan keamanan'],
            ['nama_kategori' => 'Kantor', 'deskripsi' => 'Peralatan administrasi kantor'],
            ['nama_kategori' => 'Dapur', 'deskripsi' => 'Peralatan dapur dan pantry'],
        ];

        foreach ($kategoriData as $kategori) {
            MasterKategori::create($kategori);
        }

        // Seed Master Lokasi
        $lokasiData = [
            ['nama_lokasi' => 'Ruang Ibadah Utama', 'keterangan_lokasi' => 'Tempat ibadah minggu', 'gedung' => 'Gedung A', 'lantai' => '1', 'ruangan' => 'Sanctuary'],
            ['nama_lokasi' => 'Ruang Paduan Suara', 'keterangan_lokasi' => 'Ruang latihan paduan suara', 'gedung' => 'Gedung A', 'lantai' => '2', 'ruangan' => 'Choir Room'],
            ['nama_lokasi' => 'Ruang Multimedia', 'keterangan_lokasi' => 'Ruang operator multimedia', 'gedung' => 'Gedung A', 'lantai' => '2', 'ruangan' => 'Multimedia'],
            ['nama_lokasi' => 'Kantor Administrasi', 'keterangan_lokasi' => 'Kantor staff gereja', 'gedung' => 'Gedung B', 'lantai' => '1', 'ruangan' => 'Office'],
            ['nama_lokasi' => 'Ruang Komisi Musik', 'keterangan_lokasi' => 'Ruang penyimpanan alat musik', 'gedung' => 'Gedung B', 'lantai' => '2', 'ruangan' => 'Music Storage'],
            ['nama_lokasi' => 'Aula Serbaguna', 'keterangan_lokasi' => 'Ruang untuk acara besar', 'gedung' => 'Gedung C', 'lantai' => '1', 'ruangan' => 'Hall'],
            ['nama_lokasi' => 'Ruang Anak', 'keterangan_lokasi' => 'Ruang sekolah minggu', 'gedung' => 'Gedung C', 'lantai' => '2', 'ruangan' => 'Sunday School'],
            ['nama_lokasi' => 'Dapur', 'keterangan_lokasi' => 'Dapur gereja', 'gedung' => 'Gedung C', 'lantai' => '1', 'ruangan' => 'Kitchen'],
            ['nama_lokasi' => 'Gudang', 'keterangan_lokasi' => 'Gudang penyimpanan', 'gedung' => 'Gedung D', 'lantai' => '1', 'ruangan' => 'Storage'],
            ['nama_lokasi' => 'Ruang Doa', 'keterangan_lokasi' => 'Ruang untuk doa pribadi', 'gedung' => 'Gedung A', 'lantai' => '1', 'ruangan' => 'Prayer Room'],
        ];

        foreach ($lokasiData as $lokasi) {
            MasterLokasi::create($lokasi);
        }

        // Seed Master Kondisi
        $kondisiData = [
            ['nama_kondisi' => 'Baik Sekali', 'keterangan' => 'Kondisi sempurna, seperti baru', 'kode_warna' => 'green', 'urutan' => 1],
            ['nama_kondisi' => 'Baik', 'keterangan' => 'Kondisi bagus, berfungsi normal', 'kode_warna' => 'blue', 'urutan' => 2],
            ['nama_kondisi' => 'Cukup', 'keterangan' => 'Masih bisa digunakan, perlu perhatian', 'kode_warna' => 'yellow', 'urutan' => 3],
            ['nama_kondisi' => 'Rusak Ringan', 'keterangan' => 'Ada kerusakan kecil, perlu perbaikan', 'kode_warna' => 'orange', 'urutan' => 4],
            ['nama_kondisi' => 'Rusak Berat', 'keterangan' => 'Kerusakan parah, perlu penggantian', 'kode_warna' => 'red', 'urutan' => 5],
        ];

        foreach ($kondisiData as $kondisi) {
            MasterKondisi::create($kondisi);
        }

        // Seed Master Pengelola
        $pengelolaData = [
            ['nama_pengelola' => 'Pdt. Jonathan Sitorus', 'jabatan' => 'Gembala Sidang', 'departemen' => 'Pelayanan', 'kontak' => '081234567890', 'email' => 'jonathan@gereja.com'],
            ['nama_pengelola' => 'Bpk. Daniel Lumbantobing', 'jabatan' => 'Ketua Majelis', 'departemen' => 'Majelis', 'kontak' => '081234567891', 'email' => 'daniel@gereja.com'],
            ['nama_pengelola' => 'Ibu. Sarah Hutabarat', 'jabatan' => 'Bendahara', 'departemen' => 'Keuangan', 'kontak' => '081234567892', 'email' => 'sarah@gereja.com'],
            ['nama_pengelola' => 'Bpk. Michael Panjaitan', 'jabatan' => 'Koordinator Multimedia', 'departemen' => 'Multimedia', 'kontak' => '081234567893', 'email' => 'michael@gereja.com'],
            ['nama_pengelola' => 'Ibu. Grace Simanjuntak', 'jabatan' => 'Koordinator Musik', 'departemen' => 'Musik', 'kontak' => '081234567894', 'email' => 'grace@gereja.com'],
            ['nama_pengelola' => 'Bpk. David Sinaga', 'jabatan' => 'Kepala Administrasi', 'departemen' => 'Administrasi', 'kontak' => '081234567895', 'email' => 'david@gereja.com'],
            ['nama_pengelola' => 'Ibu. Ruth Manurung', 'jabatan' => 'Koordinator Sekolah Minggu', 'departemen' => 'Anak', 'kontak' => '081234567896', 'email' => 'ruth@gereja.com'],
            ['nama_pengelola' => 'Bpk. Samuel Siahaan', 'jabatan' => 'Koordinator Keamanan', 'departemen' => 'Keamanan', 'kontak' => '081234567897', 'email' => 'samuel@gereja.com'],
        ];

        foreach ($pengelolaData as $pengelola) {
            MasterPengelola::create($pengelola);
        }

        // Seed Data Aset Kolektif (30+ items)
        $asetData = [
            // Sound System & Elektronik
            [
                'nama_aset' => 'Mixer Audio Yamaha MG16XU',
                'kategori_id' => 3,
                'deskripsi_aset' => 'Mixer audio 16 channel dengan USB interface',
                'ukuran' => '49.8 x 18.3 x 56.3 cm',
                'deskripsi_ukuran_bentuk' => 'Mixer console standar rack mount',
                'lokasi_id' => 3,
                'kegunaan' => 'Mixing audio untuk ibadah',
                'keterangan_kegunaan' => 'Digunakan setiap minggu untuk ibadah',
                'jumlah_barang' => 1,
                'tipe_grup' => 'individual',
                'budget' => 15000000,
                'keterangan_budget' => 'Dana kas gereja',
                'pengelola_id' => 4,
                'tahun_pengadaan' => 2023,
                'nilai_pengadaan_total' => 14500000,
                'nilai_pengadaan_per_unit' => 14500000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'Speaker JBL PRX815W',
                'kategori_id' => 3,
                'deskripsi_aset' => 'Speaker aktif 15 inch dengan wifi control',
                'ukuran' => '45 x 68 x 48 cm',
                'deskripsi_ukuran_bentuk' => 'Speaker aktif portable',
                'lokasi_id' => 1,
                'kegunaan' => 'Sound system utama',
                'keterangan_kegunaan' => 'Main speaker untuk ibadah minggu',
                'jumlah_barang' => 2,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Sepasang left-right',
                'budget' => 30000000,
                'keterangan_budget' => 'Bantuan jemaat',
                'pengelola_id' => 4,
                'tahun_pengadaan' => 2024,
                'nilai_pengadaan_total' => 28000000,
                'nilai_pengadaan_per_unit' => 14000000,
                'kondisi_id' => 1,
            ],
            [
                'nama_aset' => 'Microphone Shure SM58',
                'kategori_id' => 3,
                'deskripsi_aset' => 'Microphone dinamik vokal professional',
                'ukuran' => '16.2 cm',
                'deskripsi_ukuran_bentuk' => 'Microphone kabel standar',
                'lokasi_id' => 1,
                'kegunaan' => 'Microphone vokal',
                'keterangan_kegunaan' => 'Untuk pendeta dan penyanyi',
                'jumlah_barang' => 6,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 6 microphone',
                'budget' => 12000000,
                'keterangan_budget' => 'Dana kas gereja',
                'pengelola_id' => 4,
                'tahun_pengadaan' => 2022,
                'nilai_pengadaan_total' => 11400000,
                'nilai_pengadaan_per_unit' => 1900000,
                'kondisi_id' => 2,
            ],
            // Multimedia
            [
                'nama_aset' => 'Proyektor Epson EB-2250U',
                'kategori_id' => 4,
                'deskripsi_aset' => 'Proyektor WUXGA 5000 lumens',
                'ukuran' => '48.9 x 37.9 x 16.1 cm',
                'deskripsi_ukuran_bentuk' => 'Proyektor ceiling mount',
                'lokasi_id' => 1,
                'kegunaan' => 'Proyeksi lirik dan presentasi',
                'keterangan_kegunaan' => 'Main screen untuk ibadah',
                'jumlah_barang' => 1,
                'tipe_grup' => 'individual',
                'budget' => 35000000,
                'keterangan_budget' => 'Bantuan donatur',
                'pengelola_id' => 4,
                'tahun_pengadaan' => 2023,
                'nilai_pengadaan_total' => 33500000,
                'nilai_pengadaan_per_unit' => 33500000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'LED Screen P3 Indoor',
                'kategori_id' => 4,
                'deskripsi_aset' => 'LED screen indoor 4x2 meter',
                'ukuran' => '400 x 200 cm',
                'deskripsi_ukuran_bentuk' => 'LED panel modular',
                'lokasi_id' => 1,
                'kegunaan' => 'Display visual utama',
                'keterangan_kegunaan' => 'Background stage untuk ibadah',
                'jumlah_barang' => 1,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set lengkap dengan controller',
                'budget' => 85000000,
                'keterangan_budget' => 'Proyek khusus',
                'pengelola_id' => 4,
                'tahun_pengadaan' => 2024,
                'nilai_pengadaan_total' => 82000000,
                'nilai_pengadaan_per_unit' => 82000000,
                'kondisi_id' => 1,
            ],
            [
                'nama_aset' => 'Kamera PTZ Canon CR-N500',
                'kategori_id' => 4,
                'deskripsi_aset' => 'PTZ camera 4K untuk live streaming',
                'ukuran' => '17.5 x 23.6 x 21.9 cm',
                'deskripsi_ukuran_bentuk' => 'Kamera PTZ dengan remote control',
                'lokasi_id' => 1,
                'kegunaan' => 'Recording dan streaming ibadah',
                'keterangan_kegunaan' => 'Untuk YouTube channel gereja',
                'jumlah_barang' => 2,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 2 kamera dengan controller',
                'budget' => 40000000,
                'keterangan_budget' => 'Dana multimedia',
                'pengelola_id' => 4,
                'tahun_pengadaan' => 2024,
                'nilai_pengadaan_total' => 38500000,
                'nilai_pengadaan_per_unit' => 19250000,
                'kondisi_id' => 1,
            ],
            // Alat Musik
            [
                'nama_aset' => 'Piano Digital Yamaha CLP-775',
                'kategori_id' => 5,
                'deskripsi_aset' => 'Digital piano 88 keys dengan wooden keys',
                'ukuran' => '146 x 46 x 93 cm',
                'deskripsi_ukuran_bentuk' => 'Piano cabinet style',
                'lokasi_id' => 1,
                'kegunaan' => 'Iringan musik ibadah',
                'keterangan_kegunaan' => 'Keyboard utama untuk pujian',
                'jumlah_barang' => 1,
                'tipe_grup' => 'individual',
                'budget' => 45000000,
                'keterangan_budget' => 'Sumbangan keluarga',
                'pengelola_id' => 5,
                'tahun_pengadaan' => 2023,
                'nilai_pengadaan_total' => 43500000,
                'nilai_pengadaan_per_unit' => 43500000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'Drum Set Tama Superstar',
                'kategori_id' => 5,
                'deskripsi_aset' => 'Drum set 5 piece dengan hardware dan cymbal',
                'ukuran' => 'Standard drum set',
                'deskripsi_ukuran_bentuk' => 'Bass 22", Tom 10" & 12", Floor Tom 16", Snare 14"',
                'lokasi_id' => 1,
                'kegunaan' => 'Iringan musik pujian',
                'keterangan_kegunaan' => 'Drum set untuk worship team',
                'jumlah_barang' => 1,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set lengkap dengan cymbal dan hardware',
                'budget' => 25000000,
                'keterangan_budget' => 'Dana komisi musik',
                'pengelola_id' => 5,
                'tahun_pengadaan' => 2022,
                'nilai_pengadaan_total' => 23800000,
                'nilai_pengadaan_per_unit' => 23800000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'Gitar Akustik Yamaha FG830',
                'kategori_id' => 5,
                'deskripsi_aset' => 'Gitar akustik folk natural',
                'ukuran' => 'Dreadnought body',
                'deskripsi_ukuran_bentuk' => 'Gitar akustik standar',
                'lokasi_id' => 5,
                'kegunaan' => 'Iringan pujian',
                'keterangan_kegunaan' => 'Untuk worship team dan pemuda',
                'jumlah_barang' => 4,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 4 gitar',
                'budget' => 16000000,
                'keterangan_budget' => 'Dana komisi musik',
                'pengelola_id' => 5,
                'tahun_pengadaan' => 2021,
                'nilai_pengadaan_total' => 15200000,
                'nilai_pengadaan_per_unit' => 3800000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'Bass Elektrik Ibanez SR300E',
                'kategori_id' => 5,
                'deskripsi_aset' => 'Bass elektrik 4 string dengan active pickup',
                'ukuran' => 'Standard bass guitar',
                'deskripsi_ukuran_bentuk' => 'Bass elektrik standar',
                'lokasi_id' => 5,
                'kegunaan' => 'Iringan musik pujian',
                'keterangan_kegunaan' => 'Bass untuk worship team',
                'jumlah_barang' => 2,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 2 bass dengan ampli',
                'budget' => 12000000,
                'keterangan_budget' => 'Dana komisi musik',
                'pengelola_id' => 5,
                'tahun_pengadaan' => 2022,
                'nilai_pengadaan_total' => 11400000,
                'nilai_pengadaan_per_unit' => 5700000,
                'kondisi_id' => 2,
            ],
            // Furniture
            [
                'nama_aset' => 'Kursi Jemaat Kayu Jati',
                'kategori_id' => 2,
                'deskripsi_aset' => 'Kursi jemaat kayu jati dengan sandaran',
                'ukuran' => '60 x 45 x 90 cm per unit',
                'deskripsi_ukuran_bentuk' => 'Kursi individual dengan sandaran tinggi',
                'lokasi_id' => 1,
                'kegunaan' => 'Tempat duduk jemaat',
                'keterangan_kegunaan' => 'Kursi untuk ibadah minggu',
                'jumlah_barang' => 200,
                'tipe_grup' => 'grup',
                'keterangan_tipe_grup' => 'Set 200 kursi untuk sanctuary',
                'budget' => 100000000,
                'keterangan_budget' => 'Proyek renovasi',
                'pengelola_id' => 2,
                'tahun_pengadaan' => 2020,
                'nilai_pengadaan_total' => 95000000,
                'nilai_pengadaan_per_unit' => 475000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'Meja Administrasi',
                'kategori_id' => 9,
                'deskripsi_aset' => 'Meja kerja kantor dengan laci',
                'ukuran' => '120 x 70 x 75 cm',
                'deskripsi_ukuran_bentuk' => 'Meja kerja standar kantor',
                'lokasi_id' => 4,
                'kegunaan' => 'Meja kerja staff',
                'keterangan_kegunaan' => 'Untuk administrasi gereja',
                'jumlah_barang' => 5,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 5 meja untuk staff',
                'budget' => 10000000,
                'keterangan_budget' => 'Dana operasional',
                'pengelola_id' => 6,
                'tahun_pengadaan' => 2021,
                'nilai_pengadaan_total' => 9500000,
                'nilai_pengadaan_per_unit' => 1900000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'Lemari Arsip Besi',
                'kategori_id' => 9,
                'deskripsi_aset' => 'Lemari arsip 4 laci dengan kunci',
                'ukuran' => '45 x 62 x 132 cm',
                'deskripsi_ukuran_bentuk' => 'Lemari arsip besi 4 laci',
                'lokasi_id' => 4,
                'kegunaan' => 'Penyimpanan dokumen',
                'keterangan_kegunaan' => 'Untuk arsip administrasi',
                'jumlah_barang' => 3,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 3 lemari',
                'budget' => 9000000,
                'keterangan_budget' => 'Dana operasional',
                'pengelola_id' => 6,
                'tahun_pengadaan' => 2021,
                'nilai_pengadaan_total' => 8700000,
                'nilai_pengadaan_per_unit' => 2900000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'AC Split 2 PK Daikin',
                'kategori_id' => 1,
                'deskripsi_aset' => 'Air conditioner split 2 PK inverter',
                'ukuran' => 'Indoor unit + Outdoor unit',
                'deskripsi_ukuran_bentuk' => 'AC split standar',
                'lokasi_id' => 1,
                'kegunaan' => 'Pendingin ruangan',
                'keterangan_kegunaan' => 'AC untuk sanctuary',
                'jumlah_barang' => 4,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 4 unit AC',
                'budget' => 40000000,
                'keterangan_budget' => 'Proyek renovasi',
                'pengelola_id' => 2,
                'tahun_pengadaan' => 2022,
                'nilai_pengadaan_total' => 38000000,
                'nilai_pengadaan_per_unit' => 9500000,
                'kondisi_id' => 2,
            ],
            // Kantor & Elektronik
            [
                'nama_aset' => 'Komputer Desktop HP ProDesk',
                'kategori_id' => 1,
                'deskripsi_aset' => 'PC desktop dengan monitor 24 inch',
                'ukuran' => 'Desktop + Monitor 24"',
                'deskripsi_ukuran_bentuk' => 'PC desktop standar',
                'lokasi_id' => 4,
                'kegunaan' => 'Komputer administrasi',
                'keterangan_kegunaan' => 'Untuk pekerjaan staff',
                'jumlah_barang' => 3,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 3 PC lengkap',
                'budget' => 30000000,
                'keterangan_budget' => 'Dana IT',
                'pengelola_id' => 6,
                'tahun_pengadaan' => 2023,
                'nilai_pengadaan_total' => 28500000,
                'nilai_pengadaan_per_unit' => 9500000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'Printer Canon ImageClass MF445dw',
                'kategori_id' => 1,
                'deskripsi_aset' => 'Printer laser multifungsi monochrome',
                'ukuran' => '41 x 45 x 42 cm',
                'deskripsi_ukuran_bentuk' => 'Printer multifungsi laser',
                'lokasi_id' => 4,
                'kegunaan' => 'Printing dokumen',
                'keterangan_kegunaan' => 'Untuk cetak administrasi',
                'jumlah_barang' => 2,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 2 printer',
                'budget' => 12000000,
                'keterangan_budget' => 'Dana operasional',
                'pengelola_id' => 6,
                'tahun_pengadaan' => 2022,
                'nilai_pengadaan_total' => 11400000,
                'nilai_pengadaan_per_unit' => 5700000,
                'kondisi_id' => 2,
            ],
            // Liturgi & Dekorasi
            [
                'nama_aset' => 'Mimbar Kayu Jati',
                'kategori_id' => 7,
                'deskripsi_aset' => 'Mimbar kayu jati dengan ukiran',
                'ukuran' => '120 x 60 x 110 cm',
                'deskripsi_ukuran_bentuk' => 'Mimbar dengan desain klasik',
                'lokasi_id' => 1,
                'kegunaan' => 'Tempat berkhotbah',
                'keterangan_kegunaan' => 'Mimbar untuk pendeta',
                'jumlah_barang' => 1,
                'tipe_grup' => 'individual',
                'budget' => 15000000,
                'keterangan_budget' => 'Sumbangan jemaat',
                'pengelola_id' => 1,
                'tahun_pengadaan' => 2019,
                'nilai_pengadaan_total' => 14500000,
                'nilai_pengadaan_per_unit' => 14500000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'Meja Perjamuan Kudus',
                'kategori_id' => 7,
                'deskripsi_aset' => 'Meja perjamuan kudus kayu jati',
                'ukuran' => '200 x 80 x 85 cm',
                'deskripsi_ukuran_bentuk' => 'Meja persegi panjang',
                'lokasi_id' => 1,
                'kegunaan' => 'Perjamuan kudus',
                'keterangan_kegunaan' => 'Untuk sakramen perjamuan kudus',
                'jumlah_barang' => 1,
                'tipe_grup' => 'individual',
                'budget' => 12000000,
                'keterangan_budget' => 'Dana gereja',
                'pengelola_id' => 1,
                'tahun_pengadaan' => 2019,
                'nilai_pengadaan_total' => 11500000,
                'nilai_pengadaan_per_unit' => 11500000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'Salib Kayu Besar',
                'kategori_id' => 6,
                'deskripsi_aset' => 'Salib kayu besar untuk dinding',
                'ukuran' => '200 x 100 cm',
                'deskripsi_ukuran_bentuk' => 'Salib kayu wall mounted',
                'lokasi_id' => 1,
                'kegunaan' => 'Dekorasi sanctuary',
                'keterangan_kegunaan' => 'Simbol iman di dinding depan',
                'jumlah_barang' => 1,
                'tipe_grup' => 'individual',
                'budget' => 8000000,
                'keterangan_budget' => 'Sumbangan keluarga',
                'pengelola_id' => 2,
                'tahun_pengadaan' => 2019,
                'nilai_pengadaan_total' => 7500000,
                'nilai_pengadaan_per_unit' => 7500000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'Banner Stand Roll Up',
                'kategori_id' => 6,
                'deskripsi_aset' => 'Banner stand portable roll up',
                'ukuran' => '85 x 200 cm',
                'deskripsi_ukuran_bentuk' => 'Roll up banner portable',
                'lokasi_id' => 6,
                'kegunaan' => 'Display informasi acara',
                'keterangan_kegunaan' => 'Untuk promosi acara gereja',
                'jumlah_barang' => 5,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 5 banner stand',
                'budget' => 5000000,
                'keterangan_budget' => 'Dana promosi',
                'pengelola_id' => 6,
                'tahun_pengadaan' => 2023,
                'nilai_pengadaan_total' => 4500000,
                'nilai_pengadaan_per_unit' => 900000,
                'kondisi_id' => 1,
            ],
            // Dapur
            [
                'nama_aset' => 'Kulkas 2 Pintu Samsung',
                'kategori_id' => 10,
                'deskripsi_aset' => 'Kulkas 2 pintu 500 liter',
                'ukuran' => '91 x 79 x 179 cm',
                'deskripsi_ukuran_bentuk' => 'Kulkas besar 2 pintu',
                'lokasi_id' => 8,
                'kegunaan' => 'Penyimpanan makanan',
                'keterangan_kegunaan' => 'Untuk fellowship dan acara',
                'jumlah_barang' => 2,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 2 kulkas',
                'budget' => 24000000,
                'keterangan_budget' => 'Dana sosial',
                'pengelola_id' => 2,
                'tahun_pengadaan' => 2022,
                'nilai_pengadaan_total' => 22800000,
                'nilai_pengadaan_per_unit' => 11400000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'Dispenser Air Panas Dingin',
                'kategori_id' => 10,
                'deskripsi_aset' => 'Dispenser standing 3 kran',
                'ukuran' => '35 x 35 x 100 cm',
                'deskripsi_ukuran_bentuk' => 'Dispenser standing',
                'lokasi_id' => 8,
                'kegunaan' => 'Penyediaan air minum',
                'keterangan_kegunaan' => 'Air minum untuk jemaat',
                'jumlah_barang' => 4,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 4 dispenser',
                'budget' => 8000000,
                'keterangan_budget' => 'Dana operasional',
                'pengelola_id' => 2,
                'tahun_pengadaan' => 2021,
                'nilai_pengadaan_total' => 7600000,
                'nilai_pengadaan_per_unit' => 1900000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'Microwave Oven Sharp',
                'kategori_id' => 10,
                'deskripsi_aset' => 'Microwave 25 liter',
                'ukuran' => '48 x 40 x 28 cm',
                'deskripsi_ukuran_bentuk' => 'Microwave standar',
                'lokasi_id' => 8,
                'kegunaan' => 'Memanaskan makanan',
                'keterangan_kegunaan' => 'Untuk fellowship',
                'jumlah_barang' => 2,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 2 microwave',
                'budget' => 4000000,
                'keterangan_budget' => 'Dana operasional',
                'pengelola_id' => 2,
                'tahun_pengadaan' => 2022,
                'nilai_pengadaan_total' => 3800000,
                'nilai_pengadaan_per_unit' => 1900000,
                'kondisi_id' => 2,
            ],
            // Keamanan
            [
                'nama_aset' => 'CCTV Hikvision 4MP',
                'kategori_id' => 8,
                'deskripsi_aset' => 'CCTV IP camera 4 megapixel dengan night vision',
                'ukuran' => '14 x 14 x 10 cm per unit',
                'deskripsi_ukuran_bentuk' => 'Dome camera',
                'lokasi_id' => 1,
                'kegunaan' => 'Keamanan dan monitoring',
                'keterangan_kegunaan' => 'Sistem keamanan gereja',
                'jumlah_barang' => 12,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 12 camera dengan NVR',
                'budget' => 30000000,
                'keterangan_budget' => 'Proyek keamanan',
                'pengelola_id' => 8,
                'tahun_pengadaan' => 2023,
                'nilai_pengadaan_total' => 28500000,
                'nilai_pengadaan_per_unit' => 2375000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'APAR 6 Kg Powder',
                'kategori_id' => 8,
                'deskripsi_aset' => 'Alat pemadam api ringan powder 6kg',
                'ukuran' => '55 cm tinggi',
                'deskripsi_ukuran_bentuk' => 'Tabung APAR standar',
                'lokasi_id' => 1,
                'kegunaan' => 'Proteksi kebakaran',
                'keterangan_kegunaan' => 'Untuk keselamatan gedung',
                'jumlah_barang' => 8,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 8 APAR untuk seluruh gedung',
                'budget' => 8000000,
                'keterangan_budget' => 'Dana keamanan',
                'pengelola_id' => 8,
                'tahun_pengadaan' => 2024,
                'nilai_pengadaan_total' => 7600000,
                'nilai_pengadaan_per_unit' => 950000,
                'kondisi_id' => 1,
            ],
            // Anak & Pendidikan
            [
                'nama_aset' => 'Meja Belajar Anak',
                'kategori_id' => 2,
                'deskripsi_aset' => 'Meja belajar anak warna-warni',
                'ukuran' => '60 x 60 x 55 cm',
                'deskripsi_ukuran_bentuk' => 'Meja bulat anak-anak',
                'lokasi_id' => 7,
                'kegunaan' => 'Meja sekolah minggu',
                'keterangan_kegunaan' => 'Untuk kelas anak-anak',
                'jumlah_barang' => 10,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 10 meja dengan 40 kursi',
                'budget' => 15000000,
                'keterangan_budget' => 'Dana sekolah minggu',
                'pengelola_id' => 7,
                'tahun_pengadaan' => 2023,
                'nilai_pengadaan_total' => 14250000,
                'nilai_pengadaan_per_unit' => 1425000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'Papan Tulis Whiteboard',
                'kategori_id' => 9,
                'deskripsi_aset' => 'Whiteboard magnetic 120x240cm',
                'ukuran' => '120 x 240 cm',
                'deskripsi_ukuran_bentuk' => 'Papan tulis besar',
                'lokasi_id' => 7,
                'kegunaan' => 'Mengajar sekolah minggu',
                'keterangan_kegunaan' => 'Untuk kelas anak',
                'jumlah_barang' => 5,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 5 whiteboard untuk kelas',
                'budget' => 7500000,
                'keterangan_budget' => 'Dana sekolah minggu',
                'pengelola_id' => 7,
                'tahun_pengadaan' => 2022,
                'nilai_pengadaan_total' => 7125000,
                'nilai_pengadaan_per_unit' => 1425000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'Rack Sepatu Besi',
                'kategori_id' => 2,
                'deskripsi_aset' => 'Rak sepatu besi 5 tingkat',
                'ukuran' => '90 x 30 x 150 cm',
                'deskripsi_ukuran_bentuk' => 'Rak besi bertingkat',
                'lokasi_id' => 1,
                'kegunaan' => 'Penyimpanan sepatu',
                'keterangan_kegunaan' => 'Tempat sepatu jemaat',
                'jumlah_barang' => 6,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 6 rak',
                'budget' => 6000000,
                'keterangan_budget' => 'Dana operasional',
                'pengelola_id' => 2,
                'tahun_pengadaan' => 2021,
                'nilai_pengadaan_total' => 5700000,
                'nilai_pengadaan_per_unit' => 950000,
                'kondisi_id' => 2,
            ],
            [
                'nama_aset' => 'Standing Fan Miyako',
                'kategori_id' => 1,
                'deskripsi_aset' => 'Kipas angin berdiri 16 inch',
                'ukuran' => '16 inch',
                'deskripsi_ukuran_bentuk' => 'Standing fan',
                'lokasi_id' => 6,
                'kegunaan' => 'Sirkulasi udara',
                'keterangan_kegunaan' => 'Untuk aula dan ruang meeting',
                'jumlah_barang' => 8,
                'tipe_grup' => 'set',
                'keterangan_tipe_grup' => 'Set 8 kipas',
                'budget' => 4000000,
                'keterangan_budget' => 'Dana operasional',
                'pengelola_id' => 2,
                'tahun_pengadaan' => 2021,
                'nilai_pengadaan_total' => 3800000,
                'nilai_pengadaan_per_unit' => 475000,
                'kondisi_id' => 3,
            ],
        ];

        foreach ($asetData as $aset) {
            DataAsetKolektif::create($aset);
        }

        $this->command->info('Master data dan aset kolektif berhasil di-seed!');
        $this->command->info('Total kategori: ' . MasterKategori::count());
        $this->command->info('Total lokasi: ' . MasterLokasi::count());
        $this->command->info('Total kondisi: ' . MasterKondisi::count());
        $this->command->info('Total pengelola: ' . MasterPengelola::count());
        $this->command->info('Total aset kolektif: ' . DataAsetKolektif::count());
    }
}
